/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('@arco-design/web-vue')['Button']
    AButtonGroup: typeof import('@arco-design/web-vue')['ButtonGroup']
    ACard: typeof import('@arco-design/web-vue')['Card']
    ACol: typeof import('@arco-design/web-vue')['Col']
    AImagePreviewGroup: typeof import('@arco-design/web-vue')['ImagePreviewGroup']
    AList: typeof import('@arco-design/web-vue')['List']
    AListItem: typeof import('@arco-design/web-vue')['ListItem']
    ArcoDark: typeof import('./.vitepress/theme/components/arcoDark.vue')['default']
    ARow: typeof import('@arco-design/web-vue')['Row']
    ArticleMetadata: typeof import('./.vitepress/theme/components/articleMetadata.vue')['default']
    ATag: typeof import('@arco-design/web-vue')['Tag']
    Comment: typeof import('./.vitepress/theme/components/comment.vue')['default']
    FootBefore: typeof import('./.vitepress/theme/components/footBefore.vue')['default']
    Heatmap: typeof import('./.vitepress/theme/components/heatmap.vue')['default']
    IconShareAlt: typeof import('@arco-design/web-vue/es/icon')['IconShareAlt']
    IconTrophy: typeof import('@arco-design/web-vue/es/icon')['IconTrophy']
    ImageViewer: typeof import('./.vitepress/theme/components/imageViewer.vue')['default']
    MNavLink: typeof import('./.vitepress/theme/components/mNavLink.vue')['default']
    MNavLinks: typeof import('./.vitepress/theme/components/mNavLinks.vue')['default']
    PostCopyright: typeof import('./.vitepress/theme/components/postCopyright.vue')['default']
    Redirect: typeof import('./.vitepress/theme/components/redirect.vue')['default']
    Tag: typeof import('./.vitepress/theme/components/tag.vue')['default']
    WordCloud: typeof import('./.vitepress/theme/components/wordCloud.vue')['default']
  }
}
