/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AImagePreviewGroup: typeof import('@arco-design/web-vue')['ImagePreviewGroup']
    ArcoDark: typeof import('./.vitepress/theme/components/arcoDark.vue')['default']
    ArticleMetadata: typeof import('./.vitepress/theme/components/articleMetadata.vue')['default']
    ATag: typeof import('@arco-design/web-vue')['Tag']
    Comment: typeof import('./.vitepress/theme/components/comment.vue')['default']
    IconShareAlt: typeof import('@arco-design/web-vue/es/icon')['IconShareAlt']
    IconTrophy: typeof import('@arco-design/web-vue/es/icon')['IconTrophy']
    ImageViewer: typeof import('./.vitepress/theme/components/imageViewer.vue')['default']
    MNavLink: typeof import('./.vitepress/theme/components/mNavLink.vue')['default']
    MNavLinks: typeof import('./.vitepress/theme/components/mNavLinks.vue')['default']
  }
}
